### ISSUE TITLE
KeyError: 'bytes104'

### ISSUE THREAD

**Issue by xiaoliqiangxxqzz** [yaohungt/Multimodal-Transformer#10]
Start loading the data....
  - Creating new train data
dataset_path data/mosei_senti_data_noalign.pkl
  - Creating new valid data
dataset_path data/mosei_senti_data_noalign.pkl
  - Creating new test data
dataset_path data/mosei_senti_data_noalign.pkl
Finish loading the data....
### Note: You are running in unaligned mode.
Traceback (most recent call last):
  File "main.py", line 151, in <module>
    test_loss = train.initiate(hyp_params, train_loader, valid_loader, test_loader)
  File "/home/xlq/Multimodal-Transformer-master/src/train.py", line 63, in initiate
    return train_model(settings, hyp_params, train_loader, valid_loader, test_loader)
  File "/home/xlq/Multimodal-Transformer-master/src/train.py", line 236, in train_model
    train(model, optimizer, criterion, ctc_a2l_module, ctc_v2l_module, ctc_a2l_optimizer, ctc_v2l_optimizer, ctc_criterion)
  File "/home/xlq/Multimodal-Transformer-master/src/train.py", line 92, in train
    for i_batch, (batch_X, batch_Y, batch_META) in enumerate(train_loader):
  File "/home/xlq/anaconda3/envs/pyth/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/xlq/anaconda3/envs/pyth/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 68, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/xlq/anaconda3/envs/pyth/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 68, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/xlq/anaconda3/envs/pyth/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 68, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/xlq/anaconda3/envs/pyth/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 68, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/xlq/anaconda3/envs/pyth/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return numpy_type_map[elem.dtype.name](list(map(py_type, batch)))
KeyError: 'bytes104'

**Comment by yaohungt** [comment]
I don't remember I have faced this issue. It seem like the problem happens in dataset.py.

What is the version of PyTorch you're using? Also, can you check if the loading of X/Y/META are correct in lines 51-53 in

https://github.com/yaohungt/Multimodal-Transformer/blob/master/src/dataset.py

**Comment by xiaoliqiangxxqzz** [comment]
> 我不记得我遇到过这个问题。看来问题出在dataset.py中。
> 
> 您使用的PyTorch是什么版本？另外，您可以检查X / Y / META的加载在第51-53行中是否正确
> 
> https://github.com/yaohungt/Multimodal-Transformer/blob/master/src/dataset.py

The version of PyTorch is 1.2.0. And when i use mosei_senti_data_noalign.pkl, error occurred:"_pickle.UnpicklingError: pickle data was truncated".So,i use  mosi_data_noalign.pkl,but that's what happened.

**Comment by yaohungt** [comment]
Do you like to re-download the data from the dropbox? I never faced the issues you have, but I will examine it more tomorrow.

**Comment by xiaoliqiangxxqzz** [comment]
> Do you like to re-download the data from the dropbox? I never faced the issues you have, but I will examine it more tomorrow.

Ok,I will re-download the data and try again

**Comment by yaohungt** [comment]
> > 我不记得我遇到过这个问题。看来问题出在dataset.py中。
> > 您使用的PyTorch是什么版本？另外，您可以检查X / Y / META的加载在第51-53行中是否正确
> > https://github.com/yaohungt/Multimodal-Transformer/blob/master/src/dataset.py
> 
> The version of PyTorch is 1.2.0. And when i use mosei_senti_data_noalign.pkl, error occurred:"_pickle.UnpicklingError: pickle data was truncated".So,i use mosi_data_noalign.pkl,but that's what happened.

By the way, it surprises me that GitHub has an automatic translation function....

**Comment by yaohungt** [comment]
I guess maybe you do not set the datapath correctly? If this is the case, it will have your above issues.

**Comment by xiaoliqiangxxqzz** [comment]
> > > 我不记得我遇到过这个问题。看来问题出在dataset.py中。
> > > 您使用的PyTorch是什么版本？另外，您可以检查X / Y / META的加载在第51-53行中是否正确
> > > https://github.com/yaohungt/Multimodal-Transformer/blob/master/src/dataset.py
> > 
> > 
> > The version of PyTorch is 1.2.0. And when i use mosei_senti_data_noalign.pkl, error occurred:"_pickle.UnpicklingError: pickle data was truncated".So,i use mosi_data_noalign.pkl,but that's what happened.
> 
> By the way, it surprises me that GitHub has an automatic translation function....

hahaha,chrome has that function not Github

**Comment by xiaoliqiangxxqzz** [comment]
> I guess maybe you do not set the datapath correctly? If this is the case, it will have your above issues.

yes, it works now.But it seems like there is some problems with mosei_senti_data_noalign.pkl.
