### ISSUE TITLE
How do you divide three data sets in to Train, Validation and Test?

### ISSUE THREAD

**Issue by shamanez** [yaohungt/Multimodal-Transformer#11]
Do you have a list of example IDs or Video IDs that you used to split datasets?

**Comment by yaohungt** [comment]
The link to the split:

https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei_std_folds.py
