### ISSUE TITLE
ValueError: Expected input batch_size (96) to match target batch_size (192)

### ISSUE THREAD

**Issue by TythonLee** [yaohungt/Multimodal-Transformer#13]
When running on unaligned IEMOCAP dataset, an error occured as "ValueError: Expected input batch_size (96) to match target batch_size (192)". Which comes from train.py  line 163. Do you know how to solve it? Thanks~

**Comment by yaohungt** [comment]
Hi, 

Can you check that do you change the flag of dataset to be 'iemocap'?

**Comment by Uooga** [comment]
I faced the same situation, and I already set --dataset iemocap, but  still got stuck in the problem, so I am wondering is there anything else that I didn't notice? I also try to reshape the output prediction to match the shape of original labels ([N,4,2]), only to find another bug. Waiting for your response, Thanks~

**Comment by yaohungt** [comment]
Hi, 

I pushed a change, can you let me know does it resolve the problem or not? I have no machine to test this right now.

**Comment by Uooga** [comment]
It works, Thanks a lot!
