### ISSUE TITLE
last_h_v = last_hs = h_vs[:,-1,:]

### ISSUE THREAD

**Issue by qniguoym** [yaohungt/Multimodal-Transformer#14]
why do you use the last timestep of sequence for concatenation?

**Comment by yaohungt** [comment]
The task is a summarization task. We summarize from the sequence(s) and perform classification/ regression on this summarization. 

Summarization can be any form; concatenating the last time steps is just one option. Note that these last time steps have a receptive field of the entire sequence length.

**Comment by qniguoym** [comment]
but the vector of last timestep only has information the last word attend?

**Comment by yaohungt** [comment]
No, the last tilmestep from the output of the encoder has a receptive field of the entire sequence length.

It attends to the entire sequence.
