### ISSUE TITLE
Could I just use text&audio to train a model?

### ISSUE THREAD

**Issue by VirtualMoon** [yaohungt/Multimodal-Transformer#18]
Hi,
I found your code says that "raise ValueError("You can only choose one of {l/v/a}only.")".
So could I just use text&audio to train a model? 
Or is it hard to modify your code?

**Comment by yaohungt** [comment]
You may need to modify the code to make it work. I don't think it is hard.

**Comment by VirtualMoon** [comment]
OK, I'll try it ,thank you very much
