### ISSUE TITLE
What is the maximum training length (in seconds) for unaligned mosei dataset ?

### ISSUE THREAD

**Issue by shamanez** [yaohungt/Multimodal-Transformer#21]
In the paper, you have mentioned like this : 

"_The unaligned CMU-MOSEI sequences are extracted at a sampling rate of 20 Hz for acoustic and 15 Hz for vision signals_"

This means you use the transcript as it is and sample the audio signal in 20hz right? So if the audio signal is 5 seconds in length you have 100 samples right?

**Comment by yaohungt** [comment]
yes

**Comment by shamanez** [comment]
So in the 20Hz range is it audible? Like quality will be super low right?

**Comment by shamanez** [comment]
Also, what is the maximum length of the text sequence since you are using word2vec representation?
