### ISSUE TITLE
How can I set these hyperparameters?

### ISSUE THREAD

**Issue by ChenBattle** [yaohungt/Multimodal-Transformer#23]
I use the default parameters to train, but the result is not as good as that in the paper.
I guess it must be a problem of hyperparameters setting.
The value of hyperparameters are introduced in the paper, but I don't know how to set these values in the code:

1. Transformers Hidden Unit Size d
2. of Crossmodal Blocks D
3. of Crossmodal Attention Heads
4. Temporal Convolution Kernel Size (L/V/A)

Could you please help me?
Thank you very much!

**Comment by yaohungt** [comment]
1. and 4. are in src/models.py
2. and 3. are in main.py

**Comment by CindyTing** [comment]
Hello, I also have same question. 
Does the "# of Crossmodal Blocks D"  means "--nlevels" in main.py?
Does the "Transformers Hidden Unit Size d" means "self.d_l, self.d_a, self.d_v" in src/models.py?

Could you help me out of here?
Thanks a lot!
