### ISSUE TITLE
In paper, not showed Emotion Prediction for CMU-MOSEI Dataset

### ISSUE THREAD

**Issue by chayan-dhaddha** [yaohungt/Multimodal-Transformer#24]
Is there any specific reason why you didn't mention results for Emotion Prediction for CMU-MOSEI Dataset? If yes, then why? If no, why you never thought of it? Thanks

**Comment by yaohungt** [comment]
You can obtain the results by directly applying the code. The reason why we do not provide CMU-MOSEI is that the labeling of it is skewed. To get a sense of it, always predicting neutral emotion in the CMU-MOSEI obtains nearly perfect prediction (90% accuracy). It requires additional efforts such as solving the label imbalance problem which is not our focus.
