### ISSUE TITLE
Details about audio feature extraction

### ISSUE THREAD

**Issue by DesmonDay** [yaohungt/Multimodal-Transformer#25]
Hi. I want to transfer your method to other multimodal dataset(text + audio). Can you tell me the details of extracting the audio features? I looked into https://github.com/covarep/covarep/tree/master/feature_extraction, but no idea about how to get features of 74 dimensions. Thanks!

**Comment by yaohungt** [comment]
Please see https://github.com/yaohungt/Multimodal-Transformer/issues/4

**Comment by DesmonDay** [comment]
Yes, I have already e-mailed him. But I worry that there may be no repy, so I open this issue:)



---Original---

**Comment by yaohungt** [comment]
Hey, please resend the email c.c. me and the other authors of the paper.

**Comment by DesmonDay** [comment]
Ok.

**Comment by taylor4712** [comment]
Have you received an answer and know more about the details of feature extraction/preprocessing? Since I also wanted to reproduce it myself.
