### ISSUE TITLE
Transformer intermediate values

### ISSUE THREAD

**Issue by vandana-rajan** [yaohungt/Multimodal-Transformer#28]
Hi,

In the modules/transformer.py code, in 'TransformerEncoder' forward function, the list 'intermediates' is used to collect the input value as well as the output of all encoder layers. However, it is not used later in the code. Why is that so? 

Lines 78-90

```
# encoder layers
        intermediates = [x]
        for layer in self.layers:
            if x_in_k is not None and x_in_v is not None:
                x = layer(x, x_k, x_v)
            else:
                x = layer(x)
            intermediates.append(x)

        if self.normalize:
            x = self.layer_norm(x)

        return x

```

Could you kindly let me know if this is intended or is a bug in the code or if I have not understood it correctly?

Thanks,

**Comment by LiangFeifei0920** [comment]
Intermediates is for subsequent ablation experiments, included in the paper
