### ISSUE TITLE
GradientComputation Error

### ISSUE THREAD

**Issue by arminarj** [yaohungt/Multimodal-Transformer#30]
Hi Dear @yaohungt,

It seems Pytorch 1.8  has changed some rules about the inplace-operations and [this line](https://github.com/yaohungt/Multimodal-Transformer/blob/73511527d946e3228592e1d287c4866ad159dccd/modules/multihead_attention.py#L85) of the code raises a runtime error.

```Encounter the RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation```

and based on [this link](https://discuss.pytorch.org/t/encounter-the-runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation/836/5?u=arminarj) you can fix it by only changing it to:

 ` q = q * self.scaling `

Regards

**Comment by yaohungt** [comment]
Thanks!
