### ISSUE TITLE
The "mosei_senti_data_noalign.pkl" file you provide in dropbox cannot be unzipped correctly, it seems that the zip file is broken.

### ISSUE THREAD

**Issue by ppsk1ng** [yaohungt/Multimodal-Transformer#31]
I've try winrar, 7z and Bandizip, but cannot unzip the file.

**Comment by yaohungt** [comment]
.pkl is a pickle file, not a zip file

**Comment by vpellegrain** [comment]
Yeah it is a .pkl but the whole .zip file containing it (along with other .pkl data files) on dropbox can't be unzipped properly because of this .pkl file. I get the same error when trying to unzip the whole package.

**Comment by yaohungt** [comment]
I tested just now. I received no error. I used Linux system for downloading and unzipping.

**Comment by vpellegrain** [comment]
So you downloaded and unzipping in Unix command line ? 
I wanted to do that way but couldn't find how to get the download link on dropbox to run a wget command. 
So i manually downloaded it and then tried to unzip it using either unzip command line, or manually, both did not work out, as stated here. 
So I'm currently using SDK repo to download original data.

But if you could write here proper steps in command line you used, I'd be glad to try and reproduce ! 

Thanks

**Comment by yaohungt** [comment]
wget https://www.dropbox.com/sh/hyzpgx1hp9nj37s/AADfY2s7gD_MkR76m03KS0K1a/Archive.zip?dl=1
mv 'Archive.zip?dl=1' Archive.zip
unzip Archive.zip

**Comment by vpellegrain** [comment]
Seems to work, whereas when downloaded manually, the same command 'unzip Archive.zip' threw an error. 
Thanks !

**Comment by yaohungt** [comment]
Interesting, I never download the datasets manually but I will be aware of this issue in the future
