### ISSUE TITLE
Dataset download failed

### ISSUE THREAD

**Issue by yehaizhi** [yaohungt/Multimodal-Transformer#41]
Dataset always fail when the download is almost complete.How should I solve it.

**Comment by liziming5353** [comment]
I have the same problem. Have you solved it?

**Comment by yehaizhi** [comment]
总是在最后下载不下来是吗&nbsp;




侯增辉
潍坊科技学院


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 下午4:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yaohungt/Multimodal-Transformer] Dataset download failed (#41)





 
I have the same problem. Have you solved it?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yehaizhi** [comment]
NO,Always fail when the download is almost complete

**Comment by yehaizhi** [comment]
NO，Always fail when the download is almost complete
