### ISSUE TITLE
The dataset is unavailable now. Both direct download and wget not work.  Could you please fix that?

### ISSUE THREAD

**Issue by sejmoonwei** [yaohungt/Multimodal-Transformer#50]
Can not download from [here](https://www.dropbox.com/sh/hyzpgx1hp9nj37s/AAB7FhBqJOFDw2hEyvv2ZXHxa?dl=0) and same for wget.

**Comment by sejmoonwei** [comment]
Okay. Not available in China, even with VPN.  Ask friends abroad for help.

**Comment by siuwaiwty** [comment]
I'm having the same problem as you, can you share the dataset?

**Comment by HandsomeCBX** [comment]
![image](https://github.com/yaohungt/Multimodal-Transformer/assets/148057185/16389774-daaa-4974-b1dd-d206d1b8eec4)
just download

**Comment by objk24** [comment]
> ![image](https://github.com/yaohungt/Multimodal-Transformer/assets/148057185/16389774-daaa-4974-b1dd-d206d1b8eec4) just download
hello bro，could you please share it to me ?
