### ISSUE TITLE
IEMOCAP Ddataset

### ISSUE THREAD

**Issue by BinWang28** [yaohungt/Multimodal-Transformer#6]
Hi Author,

I have loaded the IEMOCAP dataset.

Found that the size for train/val/test data are 2717/789/938. And the total is around 4K sample. But the original IEMOCAP data should consists of 10K videos? Is it because we are choosing 4 emotions out of 9 emotions or the one for downloading is incomplete?

**Comment by yaohungt** [comment]
We follow the setting from [Words can Shift: Dynamically Adjusting Word Representations Using Nonverbal Behaviors, Wang et al. (2019)]. 4 emotions (happy, sad, angry and neutral) were selected for emotion recognition. We exclude the emotions whose labels are highly skewed.

For further questions, please contact pliang@cs.cmu.edu who is in charge of data preprocessing.
