### ISSUE TITLE
multihead_attention.py

### ISSUE THREAD

**Issue by zouyi-ahu** [yaohungt/Multimodal-Transformer#9]
Can you tell me the function of “embed_dim” in the multihead_attention.py ?
thanks!

**Comment by yaohungt** [comment]
It is the dimension of the embedding in the Transformer. Precisely, it is the dimension after the self-attention/ cross-modal attention.

**Comment by zouyi-ahu** [comment]
Thank you  for your reply ！




在 2019-10-09 22:14:53，"Yao-Hung Hubert Tsai" <notifications@github.com> 写道：


Closed #9.
